-- Harden Supabase Data API: enable RLS with no policies on public tables.
-- anon / authenticated get zero rows via PostgREST.
-- Prisma (DATABASE_URL / postgres role) keeps BYPASSRLS and is unchanged.

ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserRole" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserConsent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Member" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MemberNote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Lead" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LeadActivity" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Coach" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ClassType" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ClassTypeEligibilityRule" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ClassSession" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Reservation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReservationEntitlementUsage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WaitlistEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "NotificationJob" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "NotificationDeliveryAttempt" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MembershipPlan" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MemberMembership" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MembershipBookingPolicy" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MemberMembershipBookingOverride" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CreditPack" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MemberCreditAccount" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CreditLedgerEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Card" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Payment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PaymentItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PaymentEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "_prisma_migrations" ENABLE ROW LEVEL SECURITY;
